name: Automatic Changelog Generation

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  changelog:
    name: Generate Changelog and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Changelog and Create Release
        uses: TriPSs/conventional-changelog-action@v6.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-tag: true
          git-push: false
