name: Automatic Changelog Generation

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  changelog:
    name: Generate Changelog and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Changelog and Create Release
        uses: TriPSs/conventional-changelog-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git-tag: false
          git-push: false
