name: Automatic Changelog Generation

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Holen der kompletten Historie und aller Tags
          fetch-depth: 0
          fetch-tags: true 

      - name: Generate Changelog
        uses: TriPSs/conventional-changelog-action@v6.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-tag: true
          git-push: true
          skip-version-file: true
          
          # NEU/KORREKT: Überspringt den internen 'git pull' (behebt den "clobbering"-Fehler)
          skip-git-pull: true 
          
          # NEU: Generiert das Changelog für alle existierenden Releases (von Anfang an)
          release-count: 0
