name: Automatic Changelog Generation

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Changelog
        uses: TriPSs/conventional-changelog-action@v6.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-tag: true
          git-push: true
          skip-version-file: true   # <--- wichtig für Projekte ohne package.json
