name: Automatic Changelog Generation

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Holen der kompletten Historie und aller Tags
          fetch-depth: 0
          fetch-tags: true 

      # ACHTUNG: Der Schritt zum Löschen der CHANGELOG.md WURDE HIER ENTFERNT!

      - name: Generate Changelog for new Release
        uses: TriPSs/conventional-changelog-action@v6.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-tag: true
          git-push: true
          skip-version-file: true
          skip-git-pull: true
          
          # NEU: Entfernt. Die Action sucht nun standardmäßig nach 1 Release.
          # release-count: 0
